# Generated by Django 3.2.4 on 2021-06-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='users',
        ),
    ]
