# Generated by Django 3.2.4 on 2021-06-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': [('add_user', 'Can add user'), ('delete_user', 'Can remove user'), ('edit_user', 'Can edit user'), ('view_user', 'Can view user')]},
        ),
    ]
