# Generated by Django 3.2.5 on 2021-07-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    def insert_product_types(apps, schema_editor):
        ProductType = apps.get_model('product', 'ProductType')
        product_types = [
            "Gadgets",
            "Appliances",
            "Office",
            "Clothes",
            "Tools",
            "Softwares",
            "Vehicles",
            "Foods",
            "Toys"
        ]

        for type in product_types:
            p = ProductType(name=type)
            p.save()

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_product_types),
    ]
